<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TYSS-Chaithra" failures="1" tests="8" name="Test" time="21.043" errors="0" timestamp="2023-07-17T08:34:08 IST">
  <testcase classname="testNG.TestNGPracticeTest" name="createCustomer" time="0.023">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG.TestNGPracticeTest.createCustomer(TestNGPracticeTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createCustomer -->
  <testcase classname="testNG.TestNGPracticeTest" name="modifyCustomer" time="0.0">
    <skipped/>
  </testcase> <!-- modifyCustomer -->
  <testcase classname="testNG.TestNGPracticeTest" name="deleteCustomer" time="0.0">
    <skipped/>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="pomClasses.LoginToActiTimeApp" name="loginTest" time="10.402"/>
  <testcase classname="testNG.DataProviderPractice" name="dataProviderDemo" time="0.002"/>
  <testcase classname="testNG.DataProviderPractice" name="dataProviderDemo" time="0.001"/>
  <testcase classname="testNG.DataProviderPractice" name="dataProviderDemo" time="0.001"/>
  <testcase classname="locators.LoginToActitime" name="loginToActiTimeTest" time="10.548"/>
</testsuite> <!-- Test -->
